Rails:
  Enabled: true

AllCops:
  Exclude:
  - db/schema.rb

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false
  
Metrics/LineLength:
  Max: 100
